# Generated by Django 3.1.7 on 2021-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210419_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='twitch_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
