# Generated by Django 3.1.7 on 2021-03-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210301_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_booth',
            field=models.BooleanField(default=False),
        ),
    ]
