# Generated by Django 3.1.7 on 2021-04-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210419_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='twitch_name',
            field=models.CharField(max_length=50),
        ),
    ]
