# Generated by Django 3.1.7 on 2021-04-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210419_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
